# Generated by Django 5.1.4 on 2025-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_members_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups_images/'),
        ),
    ]
