# Generated by Django 5.1.4 on 2025-01-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
    ]
