# Generated by Django 5.1.3 on 2025-01-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
