# Generated by Django 5.1.4 on 2025-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='group',
        ),
        migrations.AddField(
            model_name='chat',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
